stages:
  - release

release:
  stage: release
  only:
    - master
  script:
    - env
    - MODEL_ROOT_PATH=`pwd`
    - MACE_WORK_DIR=`mktemp -d`
    - pushd $MACE_WORK_DIR
    - git clone --recursive git@v9.git.n.xiaomi.com:deep-computing/libmace.git
    - pushd libmace
    - pushd mace
    - echo ./tools/export_lib.sh arm64-v8a cpu ${LIBMACE_PATH}/include ${LIBMACE_PATH}/lib/libmace-arm64-v8a-cpu
    - echo ./tools/export_lib.sh arm64-v8a gpu ${LIBMACE_PATH}/include ${LIBMACE_PATH}/lib/libmace-arm64-v8a-gpu
    - echo ./tools/export_lib.sh arm64-v8a dsp ${LIBMACE_PATH}/include ${LIBMACE_PATH}/lib/libmace-arm64-v8a-dsp
    - echo ./tools/export_lib.sh armeabi-v7a cpu ${LIBMACE_PATH}/include ${LIBMACE_PATH}/lib/libmace-armeabi-v7a-cpu
    - echo ./tools/export_lib.sh armeabi-v7a gpu ${LIBMACE_PATH}/include ${LIBMACE_PATH}/lib/libmace-armeabi-v7a-gpu
    - echo ./tools/export_lib.sh armeabi-v7a dsp ${LIBMACE_PATH}/include ${LIBMACE_PATH}/lib/libmace-armeabi-v7a-dsp
    - ./tools/export_lib.sh host cpu ${LIBMACE_PATH}/include ${LIBMACE_PATH}/lib/libmace-host-cpu
    - popd
    - find $MODEL_ROOT_PATH -name *.yml | grep "$TARGET_FILE_PATTERN" | xargs -L 1 -I {} echo "python tools/mace_tools.py --config='{}' --tuning=true --mode=all --round=10"
    - popd
    - popd
    - rm -rf $MACE_WORK_DIR
