stages:
  - prerequisites
  - release

prerequisites:
  stage: release
  only:
    - master
  script:
    - echo $PATH
    - which docker
    - docker ps

release:
  stage: release
  only:
    - master
  script:
    - env
    - CI_PROJECT_OUTPUT_PATH=/mace-build-output/$CI_PROJECT_NAME/$CI_BUILD_ID
    - mkdir -p $CI_PROJECT_OUTPUT_PATH
    - LAST_VALID_COMMIT_ID=`git log --format="%H" -n 1`
    - LAST_VALID_COMMIT_FILE_NUM=`git diff-tree --no-commit-id --name-only -r $LAST_VALID_COMMIT_ID | wc -l`
    - if [ "$LAST_VALID_COMMIT_FILE_NUM" -eq 0 ]; then LAST_VALID_COMMIT_ID=`git log --format="%H" -n 2 | tail -n1` ; fi
    - MODEL_ROOT_PATH=`pwd`
    - MACE_WORK_DIR=`mktemp -d`
    - pushd $MACE_WORK_DIR
    - GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@v9.git.n.xiaomi.com:deep-computing/mace.git
    - pushd mace
    - sed -i "s/docker run -d -it/docker run -d -i/g" tools/validate_tools.sh
    # Build only the changed files in the last 1 or 2 commits for default
    - if [ -z "$CI_BUILD_TRIGGERED" ]; then GET_MODEL_FILES_CMD="cd $MODEL_ROOT_PATH; git diff-tree --no-commit-id --name-only -r $LAST_VALID_COMMIT_ID | xargs -L 1 basename | { grep ".yml" || true; } |  xargs -L 1 -I {} find $MODEL_ROOT_PATH -name {}"; else GET_MODEL_FILES_CMD="find $MODEL_ROOT_PATH -name *.yml"; fi
    - if [ -z "$TARGET_SOCS" ]; then TARGET_SOCS=all; fi
    - sh -c "$GET_MODEL_FILES_CMD" | { grep -v ".gitlab-ci.yml" || true; } | { grep "$TARGET_FILE_PATTERN" || true; } | xargs -L 1 -I {} python tools/mace_tools.py --config="{}" --tuning=true --mode=all --round=10 --output_dir=$CI_PROJECT_OUTPUT_PATH --target_socs=$TARGET_SOCS
    - popd
    - popd
    - rm -rf $MACE_WORK_DIR
